image: docker:latest

variables:
  PUBLIC_KEY: your_public_key
  PRIVATE_KEY: your_private_key

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apk update && apk add --no-cache git
  - apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main libuv-dev
  - apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main nodejs npm
  - npm install

build:
  stage: build
  script:
    - docker-compose -f docker-compose.dev.yml up -d --build

test:
  stage: test
  script:
    - npx jest app.test.js

# deploy:
#   stage: deploy
#   script:
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.example.com
#     - docker tag myapp registry.example.com/myapp
#     - docker push registry.example.com/myapp
