
version: "3.8"

services:
  react:
    labels:
      - "com.docker.compose.container-number=1"
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
      target: development  
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules 
    command: npm start 
    ports:
      - 6000:6000 
